[project]
name = "backtester"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "bmonagan", email = "bernardmonagan@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "yfinance>=1.7.0",
    "pytest>=8.0",
]

[project.scripts]
backtester = "backtester:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "backtester",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src/backtester"]
